default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: fio
  password: <%= ENV['FIO_DATABASE_PASSWORD'] %>
  host: <%= ENV['FIO_DATABASE_HOST'] %>

development:
  <<: *default
  database: fio_development

test:
  <<: *default
  database: fio_test

production:
  <<: *default
  database: fio
